### ISSUE TITLE
FR: reverse operation

### ISSUE THREAD

**Issue by NdS-Research-Facilities** [funnel-io/json-normalize#17]
Can you possibly also add a json-unnormalize part, which reverses the output of json-normalize back into a hierarchy ?

**Comment by DevL** [comment]
Thanks for the suggestion. This is not something we'd actively would be working on for the time being. If you have an idea of what this would look like, you're welcome to elaborate further on the problem and solution, make a pull request., or fork this repository and develop it further as a separate package.
